/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boardingpal;

import static boardingpal.BoardingPal.conversations;
import java.awt.geom.RoundRectangle2D;
import static boardingpal.BoardingPal.loggedInUser;
import boardingpal.models.BedSpace;
import boardingpal.models.Conversation;
import boardingpal.models.User;
import boardingpal.models.Message;
import java.awt.Color;
import java.awt.Image;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gil
 */
public class ChatFrame extends javax.swing.JFrame {
    public String bedspace1;
    public String bedspace2;
    public String bedspace3;
    public String bedspace4;
    public String bedspace5;
    public String bedspace6;
    
    List<String> userConversationIds = loggedInUser.getConversationsId();
        List<Conversation> userConversations = conversations.stream()
            .filter(chat -> userConversationIds.contains(chat.getChat_id()))
            .collect(Collectors.toList());
    
    Profiledrop profileNav = new Profiledrop();
    public boolean isProfileNavDropped = false;
    boolean isOwnedByUser;
    boolean isRequestButtonOpen = false;
    /**
     * Creates new form LoggedIn
     */
    public ChatFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
        populateConversations();
    }
    
    public ChatFrame(boolean isOwnedByUser) {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
        this.isOwnedByUser = isOwnedByUser;
        populateConversations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        profileNavButton = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fButton1 = new boardingPal.FButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roundTextField2 = new boardingpal.RoundTextField();
        jPanel6 = new javax.swing.JPanel();
        convo1 = new javax.swing.JPanel();
        convoBsName1 = new javax.swing.JLabel();
        convoLatestC1 = new javax.swing.JLabel();
        convoImg1 = new javax.swing.JLabel();
        convo2 = new javax.swing.JPanel();
        convoBsName2 = new javax.swing.JLabel();
        convoLatestC2 = new javax.swing.JLabel();
        convoImg2 = new javax.swing.JLabel();
        convo3 = new javax.swing.JPanel();
        convoBsName3 = new javax.swing.JLabel();
        convoLatestC3 = new javax.swing.JLabel();
        convoImg3 = new javax.swing.JLabel();
        convo4 = new javax.swing.JPanel();
        convoBsName4 = new javax.swing.JLabel();
        convoLatestC4 = new javax.swing.JLabel();
        convoImg4 = new javax.swing.JLabel();
        convo5 = new javax.swing.JPanel();
        convoBsName5 = new javax.swing.JLabel();
        convoLatestC5 = new javax.swing.JLabel();
        convoImg5 = new javax.swing.JLabel();
        convo6 = new javax.swing.JPanel();
        convoBsName6 = new javax.swing.JLabel();
        convoLatestC6 = new javax.swing.JLabel();
        convoImg6 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        roundTextField14 = new boardingpal.RoundTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 766));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(243, 244, 247));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setMaximumSize(new java.awt.Dimension(1306, 69));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Bed Space");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 120, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Roommate");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel12.setText("Boarding");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Pal");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/message.png"))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 30, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/bell (1).png"))); // NOI18N
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel24.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, 49));

        jLabel25.setBackground(new java.awt.Color(255, 51, 51));
        jLabel25.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText("4");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 10, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText(loggedInUser.getFullName());
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, 32));

        profileNavButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/down-arrow.png"))); // NOI18N
        profileNavButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        profileNavButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileNavButtonMouseClicked(evt);
            }
        });
        jPanel5.add(profileNavButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, -1, 24));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("___________________");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 9));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/AdrianeDilaoSmallNavbarIcon.png"))); // NOI18N
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setMaximumSize(new java.awt.Dimension(1306, 69));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Select Conversation to Continue");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 620, 40));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setMaximumSize(new java.awt.Dimension(1306, 69));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Select a Conversation");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Select a Conversation");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        fButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/ArrowRight.png"))); // NOI18N
        fButton1.setText("Request to Join");
        fButton1.setFillClick(new java.awt.Color(0, 0, 0));
        fButton1.setFillOver(new java.awt.Color(0, 0, 0));
        fButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        fButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fButton1.setIconTextGap(10);
        fButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButton1MouseClicked(evt);
            }
        });
        fButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(fButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(fButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel6.setHorizontalAlignment(SwingConstants.CENTER);
        fButton1.setVisible(isRequestButtonOpen);

        jPanel9.setBackground(new java.awt.Color(243, 244, 247));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setMaximumSize(new java.awt.Dimension(1306, 69));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel11.setMaximumSize(new java.awt.Dimension(1306, 69));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        jLabel1.setText("Messages");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/arrow-left.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/ell.png"))); // NOI18N
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 30, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/search.png"))); // NOI18N
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, -1));

        roundTextField2.setBackground(new java.awt.Color(135, 135, 135));
        roundTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 55, 15, 55));
        roundTextField2.setForeground(new java.awt.Color(153, 153, 153));
        roundTextField2.setText("Search Messages");
        roundTextField2.setFillColor(new java.awt.Color(255, 255, 255));
        roundTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roundTextField2.setLineColor(new java.awt.Color(255, 255, 255));
        roundTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTextField2ActionPerformed(evt);
            }
        });
        jPanel9.add(roundTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, 60));

        jPanel6.setBackground(new java.awt.Color(243, 244, 247));

        convo1.setBackground(new java.awt.Color(255, 255, 255));
        convo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo1MouseClicked(evt);
            }
        });

        convoBsName1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName1.setText("Bedspace Name");

        convoLatestC1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC1.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC1.setText("Bedspace Name");

        convoImg1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo1Layout = new javax.swing.GroupLayout(convo1);
        convo1.setLayout(convo1Layout);
        convo1Layout.setHorizontalGroup(
            convo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convo1Layout.setVerticalGroup(
            convo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo1Layout.createSequentialGroup()
                        .addComponent(convoBsName1)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(convoImg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        convo2.setBackground(new java.awt.Color(255, 255, 255));
        convo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo2MouseClicked(evt);
            }
        });

        convoBsName2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName2.setText("Bedspace Name");

        convoLatestC2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC2.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC2.setText("Bedspace Name");

        convoImg2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo2Layout = new javax.swing.GroupLayout(convo2);
        convo2.setLayout(convo2Layout);
        convo2Layout.setHorizontalGroup(
            convo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convo2Layout.setVerticalGroup(
            convo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo2Layout.createSequentialGroup()
                        .addComponent(convoBsName2)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC2)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(convoImg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        convo3.setBackground(new java.awt.Color(255, 255, 255));
        convo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo3MouseClicked(evt);
            }
        });

        convoBsName3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName3.setText("Bedspace Name");

        convoLatestC3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC3.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC3.setText("Bedspace Name");

        convoImg3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo3Layout = new javax.swing.GroupLayout(convo3);
        convo3.setLayout(convo3Layout);
        convo3Layout.setHorizontalGroup(
            convo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convo3Layout.setVerticalGroup(
            convo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo3Layout.createSequentialGroup()
                        .addComponent(convoBsName3)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC3)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(convoImg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        convo4.setBackground(new java.awt.Color(255, 255, 255));
        convo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo4MouseClicked(evt);
            }
        });

        convoBsName4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName4.setText("Bedspace Name");

        convoLatestC4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC4.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC4.setText("Bedspace Name");

        convoImg4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo4Layout = new javax.swing.GroupLayout(convo4);
        convo4.setLayout(convo4Layout);
        convo4Layout.setHorizontalGroup(
            convo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convo4Layout.setVerticalGroup(
            convo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo4Layout.createSequentialGroup()
                        .addComponent(convoBsName4)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC4)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(convoImg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        convo5.setBackground(new java.awt.Color(255, 255, 255));
        convo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo5MouseClicked(evt);
            }
        });

        convoBsName5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName5.setText("Bedspace Name");

        convoLatestC5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC5.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC5.setText("Bedspace Name");

        convoImg5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo5Layout = new javax.swing.GroupLayout(convo5);
        convo5.setLayout(convo5Layout);
        convo5Layout.setHorizontalGroup(
            convo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        convo5Layout.setVerticalGroup(
            convo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo5Layout.createSequentialGroup()
                        .addComponent(convoBsName5)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC5)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(convoImg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        convo6.setBackground(new java.awt.Color(255, 255, 255));
        convo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convo6MouseClicked(evt);
            }
        });

        convoBsName6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        convoBsName6.setText("Bedspace Name");

        convoLatestC6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        convoLatestC6.setForeground(new java.awt.Color(102, 102, 102));
        convoLatestC6.setText("Bedspace Name");

        convoImg6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        javax.swing.GroupLayout convo6Layout = new javax.swing.GroupLayout(convo6);
        convo6.setLayout(convo6Layout);
        convo6Layout.setHorizontalGroup(
            convo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convoImg6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(convo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convoLatestC6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convoBsName6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        convo6Layout.setVerticalGroup(
            convo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convo6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(convo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convo6Layout.createSequentialGroup()
                        .addComponent(convoBsName6)
                        .addGap(0, 0, 0)
                        .addComponent(convoLatestC6)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(convoImg6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(convo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(convo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 530));

        jPanel32.setBackground(new java.awt.Color(243, 244, 247));

        roundTextField14.setBackground(new java.awt.Color(135, 135, 135));
        roundTextField14.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 55, 15, 55));
        roundTextField14.setForeground(new java.awt.Color(153, 153, 153));
        roundTextField14.setText("Send a message...");
        roundTextField14.setFillColor(new java.awt.Color(255, 255, 255));
        roundTextField14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roundTextField14.setLineColor(new java.awt.Color(255, 255, 255));
        roundTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTextField1ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(roundTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(roundTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel31.setHorizontalAlignment(SwingConstants.CENTER);
        SwingUtilities.invokeLater(() -> {
            // Get the dimensions of the JLabel after it has been rendered
            int width = jLabel31.getWidth();
            int height = jLabel31.getHeight();

            // Check if dimensions are valid
            if (width > 0 && height > 0) {
                String imageUrl = "/boardingpal/img/icons/send-icon.png";
                ImageIcon icon = new ImageIcon(getClass().getResource(imageUrl));

                // Scale the image to the JLabel's size
                Image image = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
                jLabel31.setIcon(new ImageIcon(image)); // Set the scaled image as the icon
            } else {
                System.err.println("JLabel dimensions not available!");
            }
        });

        jPanel33.setBackground(new java.awt.Color(243, 244, 247));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateConversations() {
        JPanel[] convoPanels = {convo1, convo2, convo3, convo4, convo5, convo6};
        JLabel[] convoBsNames = {convoBsName1, convoBsName2, convoBsName3, convoBsName4, convoBsName5, convoBsName6};
        JLabel[] convoLatestCs = {convoLatestC1, convoLatestC2, convoLatestC3, convoLatestC4, convoLatestC5, convoLatestC6};
        JLabel[] convoImgs = {convoImg1, convoImg2, convoImg3, convoImg4, convoImg5, convoImg6};
        for (int i = 0; i < convoPanels.length && i < userConversations.size(); i++) {
            Conversation conversation = userConversations.get(i);
            
            // Set the bedspace name
            String name = conversation.getMembers().get(0).getFullName().equals(loggedInUser.getFullName()) ? conversation.getMembers().get(1).getFullName() : conversation.getMembers().get(0).getFullName();
            convoBsNames[i].setText(conversation.getTitle() + name);

            // Set the latest chat teaser
            if (!conversation.getMessages().isEmpty()) {
                Message latestMessage = conversation.getMessages().get(conversation.getMessages().size() - 1);
                convoLatestCs[i].setText(latestMessage.getMessageText());
            } else {
                convoLatestCs[i].setText("No messages yet");
            }
            
            
            BedSpace bedspace = conversation.getBedspaceOwner().getBedspace(); // Avoid multiple calls to randomUsers.get(i)

            // Construct image URL and scale the image to fit the JLabel size
            String imageUrl = "/boardingpal/img/browseBedspace/" + bedspace.getId() + ".png";
            ImageIcon icon = new ImageIcon(getClass().getResource(imageUrl));

            // Scale the image to the JLabel's size
            Image image = icon.getImage().getScaledInstance(convoImgs[i].getWidth(), convoImgs[i].getHeight(), Image.SCALE_SMOOTH);
            convoImgs[i].setIcon(new ImageIcon(image)); // Set the scaled image as the icon
            
            switch(i){
                case 0 -> {
                    bedspace1 = bedspace.getId();
                }
                case 1 -> {
                    bedspace2 = bedspace.getId();
                }
                case 2 -> {
                    bedspace3 = bedspace.getId();
                }
                case 3 -> {
                    bedspace4 = bedspace.getId();
                }
                case 4 -> {
                    bedspace5 = bedspace.getId();
                }
                case 5 -> {
                    bedspace6 = bedspace.getId();
                }
            }

            // Make the conversation panel visible or clickable
            convoPanels[i].setVisible(true);
        }

        // Hide unused panels
        for (int i = userConversations.size(); i < convoPanels.length; i++) {
            convoPanels[i].setVisible(false);
        }
    }
    
    public static BedSpace findBedspaceById(String id) {
        for (BedSpace bedspace : BoardingPal.bedspaces) {
            if (bedspace.getId().equals(id)) {
                return bedspace; // Return the user if the fullName matches
            }
        }
        return null; // Return null if no user with the given fullName is found
    }
    
    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        Roommate roommateFrame = new Roommate();
        roommateFrame.setVisible(true);
        roommateFrame.pack();
        roommateFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_NextMouseClicked

    private void Next1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Next1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Next1MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        
    }//GEN-LAST:event_jLabel36MouseClicked

    private void profileNavButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileNavButtonMouseClicked
        if(!isProfileNavDropped){
            isProfileNavDropped = true;
            profileNav.setVisible(true);
            profileNav.pack();
        } else {
            isProfileNavDropped = false;
            profileNav.dispose();
        }
    }//GEN-LAST:event_profileNavButtonMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        RoommateUi2 browseRoommates = new RoommateUi2();
        browseRoommates.setVisible(true);
        browseRoommates.pack();
        browseRoommates.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void roundTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField2ActionPerformed

    private void fButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButton1MouseClicked

    }//GEN-LAST:event_fButton1MouseClicked

    private void fButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButton1ActionPerformed

    private void roundTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void convo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo1MouseClicked
        populateConversationPane(0);
    }//GEN-LAST:event_convo1MouseClicked

    private void convo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo2MouseClicked
        populateConversationPane(1);
    }//GEN-LAST:event_convo2MouseClicked

    private void convo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo3MouseClicked
        populateConversationPane(2);    
    }//GEN-LAST:event_convo3MouseClicked

    private void convo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo4MouseClicked
        populateConversationPane(3);
    }//GEN-LAST:event_convo4MouseClicked

    private void convo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo5MouseClicked
        populateConversationPane(4);
    }//GEN-LAST:event_convo5MouseClicked

    private void convo6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convo6MouseClicked
        populateConversationPane(5);
    }//GEN-LAST:event_convo6MouseClicked
    
    
    
    public void populateConversationPane(int index){
        Conversation convo = userConversations.get(index);
        jLabel8.setText(convo.getTitle() + convo.getBedspaceOwner().getFullName());
        BedSpace bedspace = convo.getBedspaceOwner().getBedspace();
        String imageUrl = "/boardingpal/img/browseBedspace/" + bedspace.getId() + ".png";
        ImageIcon icon = new ImageIcon(getClass().getResource(imageUrl));

        // Scale the image to the JLabel's size
        Image image = icon.getImage().getScaledInstance(jLabel29.getWidth(), jLabel29.getHeight(), Image.SCALE_SMOOTH);
        jLabel29.setIcon(new ImageIcon(image)); // Set the scaled image as the icon
        jLabel4.setText(convo.getBedspaceOwner().getBedspace().getBedspaceName());
        jLabel6.setText(convo.getBedspaceOwner().getBedspace().getAddress());
        Image image2 = icon.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
        jLabel5.setIcon(new ImageIcon(image2)); 
        isRequestButtonOpen = true;
        fButton1.setVisible(isRequestButtonOpen);
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel convo1;
    private javax.swing.JPanel convo2;
    private javax.swing.JPanel convo3;
    private javax.swing.JPanel convo4;
    private javax.swing.JPanel convo5;
    private javax.swing.JPanel convo6;
    private javax.swing.JLabel convoBsName1;
    private javax.swing.JLabel convoBsName2;
    private javax.swing.JLabel convoBsName3;
    private javax.swing.JLabel convoBsName4;
    private javax.swing.JLabel convoBsName5;
    private javax.swing.JLabel convoBsName6;
    private javax.swing.JLabel convoImg1;
    private javax.swing.JLabel convoImg2;
    private javax.swing.JLabel convoImg3;
    private javax.swing.JLabel convoImg4;
    private javax.swing.JLabel convoImg5;
    private javax.swing.JLabel convoImg6;
    private javax.swing.JLabel convoLatestC1;
    private javax.swing.JLabel convoLatestC2;
    private javax.swing.JLabel convoLatestC3;
    private javax.swing.JLabel convoLatestC4;
    private javax.swing.JLabel convoLatestC5;
    private javax.swing.JLabel convoLatestC6;
    private boardingPal.FButton fButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel profileNavButton;
    private boardingpal.RoundTextField roundTextField1;
    private boardingpal.RoundTextField roundTextField10;
    private boardingpal.RoundTextField roundTextField11;
    private boardingpal.RoundTextField roundTextField12;
    private boardingpal.RoundTextField roundTextField13;
    private boardingpal.RoundTextField roundTextField14;
    private boardingpal.RoundTextField roundTextField2;
    private boardingpal.RoundTextField roundTextField3;
    private boardingpal.RoundTextField roundTextField4;
    private boardingpal.RoundTextField roundTextField5;
    private boardingpal.RoundTextField roundTextField6;
    private boardingpal.RoundTextField roundTextField7;
    private boardingpal.RoundTextField roundTextField8;
    private boardingpal.RoundTextField roundTextField9;
    // End of variables declaration//GEN-END:variables
}
