/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boardingpal;

import java.awt.geom.RoundRectangle2D;
import static boardingpal.LaunchApp.loggedInUser;
import boardingpal.models.User;
import java.time.LocalDate;
import javax.swing.ImageIcon;
/**
 *
 * @author Jan
 */
public class EditProfileFrame extends javax.swing.JFrame {

    boolean isOwnedByUser = false;
    /**
     * Creates new form
     */
    public EditProfileFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public EditProfileFrame(boolean isOwnedByUser) {
        this.isOwnedByUser = isOwnedByUser;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        fButton2 = new boardingPal.FButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        fButton1 = new boardingPal.FButton();
        nameTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        birthdateTf = new javax.swing.JTextField();
        genderTf = new javax.swing.JTextField();
        residenceStatusTf = new javax.swing.JTextField();
        occupationTf = new javax.swing.JTextField();
        nationalityTf = new javax.swing.JTextField();
        religionTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutTa = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/arrow-left.png"))); // NOI18N
        fButton2.setFillClick(new java.awt.Color(255, 255, 255));
        fButton2.setFillOriginal(new java.awt.Color(255, 255, 255));
        fButton2.setFillOver(new java.awt.Color(255, 255, 255));
        fButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fButton2.setLineOriginal(new java.awt.Color(204, 204, 204));
        fButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButton2MouseClicked(evt);
            }
        });
        jPanel2.add(fButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 107, 62, 62));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("About");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Roommate Details");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 240, -1, -1));

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Name");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 290, -1, -1));

        jLabel20.setBackground(new java.awt.Color(153, 153, 153));
        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Age");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 332, -1, -1));

        jLabel21.setBackground(new java.awt.Color(153, 153, 153));
        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Birthdate");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 372, -1, -1));

        jLabel22.setBackground(new java.awt.Color(153, 153, 153));
        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Gender");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 406, -1, -1));

        jLabel31.setBackground(new java.awt.Color(153, 153, 153));
        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Resident Status");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 445, -1, -1));

        jLabel32.setBackground(new java.awt.Color(153, 153, 153));
        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Occupation");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 484, -1, -1));

        jLabel33.setBackground(new java.awt.Color(153, 153, 153));
        jLabel33.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Nationality");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 524, -1, -1));

        jLabel34.setBackground(new java.awt.Color(153, 153, 153));
        jLabel34.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Religion");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(937, 565, -1, -1));

        fButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardingpal/img/icons/ArrowRight.png"))); // NOI18N
        fButton1.setText("Approve changes\n");
        fButton1.setActionCommand(isOwnedByUser ? "Edit Profile" : "Get in touch");
        fButton1.setFillClick(new java.awt.Color(0, 0, 0));
        fButton1.setFillOver(new java.awt.Color(0, 0, 0));
        fButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        fButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        fButton1.setIconTextGap(10);
        fButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fButton1MouseClicked(evt);
            }
        });
        fButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(fButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 107, 212, 61));

        nameTf.setText(loggedInUser.getFullName());
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        jPanel2.add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 291, 167, -1));

        ageTf.setText(String.valueOf(loggedInUser.getAge()));
        ageTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTfActionPerformed(evt);
            }
        });
        jPanel2.add(ageTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 331, 167, -1));

        birthdateTf.setText(loggedInUser.getBirthdate().toString());
        jPanel2.add(birthdateTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 371, 167, -1));

        genderTf.setText(loggedInUser.getGender());
        jPanel2.add(genderTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 404, 167, -1));

        residenceStatusTf.setText(loggedInUser.getResidenceStatus());
        jPanel2.add(residenceStatusTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 444, 167, -1));

        occupationTf.setText(loggedInUser.getOccupation());
        jPanel2.add(occupationTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 484, 167, -1));

        nationalityTf.setText(loggedInUser.getNationality());
        jPanel2.add(nationalityTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 525, 167, -1));

        religionTf.setText(loggedInUser.getReligion());
        jPanel2.add(religionTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1134, 566, 167, -1));

        aboutTa.setColumns(20);
        aboutTa.setRows(5);
        aboutTa.setText(loggedInUser.getAbout());
        jScrollPane1.setViewportView(aboutTa);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 290, 276, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 380, 330));
        User temp = loggedInUser;
        String imageUrl = "/boardingpal/img/browseBoardmates/" + temp.getImageUrl() + "BoardMateFind.png";
        ImageIcon icon = new ImageIcon(getClass().getResource(imageUrl));
        jLabel4.setIcon(icon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButton1ActionPerformed

    private void fButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButton1MouseClicked
        if(isOwnedByUser) {
            loggedInUser.setFullName(nameTf.getText());
            loggedInUser.setAge(Integer.parseInt(ageTf.getText()));
            loggedInUser.setBirthdate(LocalDate.parse(birthdateTf.getText()));
            loggedInUser.setGender(genderTf.getText());
            loggedInUser.setResidenceStatus(residenceStatusTf.getText());
            loggedInUser.setOccupation(occupationTf.getText());
            loggedInUser.setNationality(nationalityTf.getText());
            loggedInUser.setReligion(religionTf.getText());
            loggedInUser.setAbout(aboutTa.getText());
            
            ProfileFrame profileFrame = new ProfileFrame(isOwnedByUser);
            profileFrame.setVisible(true);
            profileFrame.setLocationRelativeTo(null);
            profileFrame.pack();
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_fButton1MouseClicked

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void ageTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTfActionPerformed

    private void fButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fButton2MouseClicked
        ProfileFrame profileFrame = new ProfileFrame(isOwnedByUser);
        profileFrame.setVisible(true);
        profileFrame.setLocationRelativeTo(null);
        profileFrame.pack();
        this.dispose();
    }//GEN-LAST:event_fButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aboutTa;
    private javax.swing.JTextField ageTf;
    private javax.swing.JTextField birthdateTf;
    private boardingPal.FButton fButton1;
    private boardingPal.FButton fButton2;
    private javax.swing.JTextField genderTf;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField nationalityTf;
    private javax.swing.JTextField occupationTf;
    private javax.swing.JTextField religionTf;
    private javax.swing.JTextField residenceStatusTf;
    // End of variables declaration//GEN-END:variables
}
